# ----------------------------------------
# Created on: Sat Nov  4 21:45:27 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "E:/project/FPGAPango/hdmi/v1.0/project/pango_sim_libraries/usim"
vmap  adc "E:/project/FPGAPango/hdmi/v1.0/project/pango_sim_libraries/adc"
vmap  ddrc "E:/project/FPGAPango/hdmi/v1.0/project/pango_sim_libraries/ddrc"
vmap  ddrphy "E:/project/FPGAPango/hdmi/v1.0/project/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "E:/project/FPGAPango/hdmi/v1.0/project/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "E:/project/FPGAPango/hdmi/v1.0/project/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "E:/project/FPGAPango/hdmi/v1.0/project/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "E:/project/FPGAPango/hdmi/v1.0/project/pango_sim_libraries/pciegen2"
vlog -work work   \
"E:/project/FPGAPango/hdmi/v1.0/src/picorv32.v" \
"E:/project/FPGAPango/hdmi/v1.0/src/picosoc/gpio.v" \
"E:/project/FPGAPango/hdmi/v1.0/src/picosoc/hdmi/hdmi_test.v" \
"E:/project/FPGAPango/hdmi/v1.0/src/picosoc/hdmi/iic_dri.v" \
"E:/project/FPGAPango/hdmi/v1.0/src/picosoc/hdmi/ms7200_ctl.v" \
"E:/project/FPGAPango/hdmi/v1.0/src/picosoc/hdmi/ms7210_ctl.v" \
"E:/project/FPGAPango/hdmi/v1.0/src/picosoc/hdmi/ms72xx_ctl.v" \
"E:/project/FPGAPango/hdmi/v1.0/src/picosoc/hdmi/pattern_vg.v" \
"E:/project/FPGAPango/hdmi/v1.0/src/picosoc/hdmi/sync_vg.v" \
"E:/project/FPGAPango/hdmi/v1.0/src/picosoc/picosoc.v" \
"E:/project/FPGAPango/hdmi/v1.0/src/picosoc/simpleuart.v" \
"E:/project/FPGAPango/hdmi/v1.0/src/picosoc/ps2.v" \
"E:/project/FPGAPango/hdmi/v1.0/ipcore/pll/pll.v" \
"E:/project/FPGAPango/hdmi/user/sim/top_tb.v" 

# ----------------------------------------
